language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
env:
  global:
    secure: gWpJB4ocJ3wPqcV+X38ZkCjvuVwJbK9/I49AuxwahR7ICeMHNdxyz/XNyo83aC0rP/E/B9gi0wnSThPeC8GK4XFgE0I9rLxEIiz+egBg6S8lECLXxFIjjdOCipSykmRA+UHR9AVZhmILyGHR5UJWebzUXQF2uoVn0ZvrTbGWDBw=
after_success:
- bash .travis/after_success
