language: clojure
lein: lein2
before_script:
- lein2 version
- ssh-keygen -N "" -f ~/.ssh/id_rsa
- cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
script: lein2 test
env:
  global:
    secure: IUj/Jo2tUSLJi4Z0l3Vokk9EDegkiceYCRQ4ecLlYcDXsfxbYrDzcxCWwtnCQeCauJrIWGtZjUbNtfdTzkDeKAIgM2mv2lV3dPnfwyZEwNvCPJ8aCbZp8M9m5HBdqs39oUvVY/3reGiDj6Tb7MgCMGaoOY/KyLwUTpKdppxzR6E=
after_success:
- bash .travis/after_success
